#include<bits/stdc++.h>
using namespace std;
string category[5]= {"Flowering Plants",
                    "Fruit Plants",
                    "Indoor Plants",
                    "Vegetable Plants",
                    "Herbal Plants"};

string season[3]={"Summer[March to June]",
                  "Rainy[July to October]",
                  "Winter[November to February]"};

int category_season[61][2]={{0,0},{1,1},{1,1},{1,1},{1,1},
                            {1,2},{1,2},{1,2},{1,2},
                            {1,3},{1,3},{1,3},{1,3},
                            {2,1},{2,1},{2,1},{2,1},
                             {2,2},{2,2},{2,2},{2,2},
                             {2,3},{2,3},{2,3},{2,3},
                            {3,1},{3,1},{3,1},{3,1},
                            {3,2},{3,2},{3,2},{3,2},
                             {3,3},{3,3},{3,3},{3,3},
                            {4,1},{4,1},{4,1},{4,1},
                            {4,2},{4,2},{4,2},{4,2},
                            {4,3},{4,3},{4,3},{4,3},
                            {5,1},{5,1},{5,1},{5,1},
                            {5,2}, {5,2}, {5,2},{5,2},
                            {5,3},{5,3},{5,3},{5,3}};

string plant[61]={" ","moss rose",//1 1
                 "golden trumpet",//1 1
                 "red frangipani",//1 1
                 "porcelainflower",//1 1
                 "mini craneflower",
                 "busy lizzie",
                 "cranberry hibiscus",
                 "malabar melastome",
                 "johnny jump up",
                 "garden cosmos",
                 "sunflower",
                 "marigold",
                 "mango",
                 "litchi",
                 "watermelon",
                 "longan",
                 "guava",
                 "rose Apple",
                 "water chestnut",
                 "sapodila",
                 "orange",
                 "pomelo",
                 "jujubi",
                 "strawberry",
                 "rubber Plant",
                 "aloe Vera",
                 "money Plant",
                 "peace Lily",
                 "rain lily",
                 "lucky Bamboo",
                 "antherium",
                 "golden Pothos",
                 "fairy Castle Cactus",
                 "ball Cactus",
                 "string of Pearls",
                 "mother of thousands",
                 "indian spinach",
                 "red amaranth",
                 "Kangkong",
                 "pumpkin",
                 "bottle Gourd",
                 "okra",
                 "cucumber",
                 "eggplant",
                 "cabbage",
                 "cauliflower",
                 "tomato",
                 "winter squash",
                 "curry Leaves",
                 "rosemary",
                 "mint",
                 "oregano",
                 "lemon Balm",
                 "brahmi",
                 "peppermint",
                 "kalmegh",
                 "turmeric",
                 "ashwagandha",
                 "lavender",
                 "coriander"};
string scientific_name[61]={" ",
                            "Portulaca grandiflora", "Allamanda cathartica", "Plumeria rubra",
        "Hoya carnosa", "Strelitzia reginae", "Impatiens walleriana",
        "Hibiscus acetosella", "Melastoma malabathricum", "Viola tricolor",
        "Cosmos bipinnatus", "Helianthus annuus", "Tagetes erecta",
        "Mangifera indica", "Litchi chinensis", "Citrullus lanatus",
        "Dimocarpus longan", "Psidium guajava", "Syzygium jambos",
        "Eleocharis dulcis", "Manilkara zapota", "Citrus sinensis",
        "Citrus maxima", "Ziziphus jujuba", "Fragaria × ananassa",
        "Ficus elastica", "Aloe barbadensis miller", "Epipremnum aureum",
        "Spathiphyllum spp.", "Zephyranthes spp.", "Dracaena sanderiana",
        "Anthurium andraeanum", "Epipremnum aureum", "Acanthocereus tetragonus",
        "Parodia magnifica", "Senecio rowleyanus", "Kalanchoe daigremontiana",
        "Basella alba", "Amaranthus cruentus", "Ipomoea aquatica",
        "Cucurbita pepo", "Lagenaria siceraria", "Abelmoschus esculentus",
        "Cucumis sativus", "Solanum melongena", "Brassica oleracea var. capitata",
        "Brassica oleracea var. botrytis", "Solanum lycopersicum", "Cucurbita maxima",
        "Murraya koenigii", "Salvia rosmarinus", "Mentha spp.",
        "Origanum vulgare", "Melissa officinalis", "Bacopa monnieri",
        "Mentha × piperita", "Andrographis paniculata", "Curcuma longa",
        "Withania somnifera", "Lavandula angustifolia", "Coriandrum sativum"};

string family[61]={" ","Portulacaceae", "Apocynaceae", "Apocynaceae",
        "Apocynaceae", "Strelitziaceae", "Balsaminaceae",
        "Malvaceae", "Melastomataceae", "Violaceae",
        "Asteraceae", "Asteraceae", "Asteraceae",
        "Anacardiaceae", "Sapindaceae", "Cucurbitaceae",
        "Sapindaceae", "Myrtaceae", "Myrtaceae",
        "Cyperaceae", "Sapotaceae", "Rutaceae",
        "Rutaceae", "Rhamnaceae", "Rosaceae",
        "Moraceae", "Asphodelaceae", "Araceae",
        "Araceae", "Amaryllidaceae", "Asparagaceae",
        "Araceae", "Cactaceae", "Cactaceae",
        "Asteraceae", "Crassulaceae", "Basellaceae",
        "Amaranthaceae", "Convolvulaceae", "Cucurbitaceae",
        "Cucurbitaceae", "Malvaceae", "Cucurbitaceae",
        "Solanaceae", "Brassicaceae", "Brassicaceae",
        "Solanaceae", "Cucurbitaceae", "Rutaceae",
        "Lamiaceae", "Lamiaceae", "Lamiaceae",
        "Lamiaceae", "Plantaginaceae", "Lamiaceae",
        "Acanthaceae", "Zingiberaceae", "Solanaceae",
        "Lamiaceae", "Apiaceae"};

string local_name[61]={" ","Moss Rose", "Golden Trumpet", "Red Frangipani",
        "Porcelainflower", "Mini Craneflower", "Busy Lizzie",
        "Cranberry Hibiscus", "Malabar Melastome", "Johnny Jump Up",
        "Garden Cosmos", "Sunflower", "Marigold",
        "Mango", "Litchi", "Watermelon",
        "Longan", "Guava", "Rose Apple",
        "Water Chestnut", "Sapodilla", "Orange",
        "Pomelo", "Jujube", "Strawberry",
        "Rubber Plant", "Aloe Vera", "Money Plant",
        "Peace Lily", "Rain Lily", "Lucky Bamboo",
        "Anthurium", "Golden Pothos", "Fairy Castle Cactus",
        "Ball Cactus", "String of Pearls", "Mother of Thousands",
        "Indian Spinach", "Red Amaranth", "Kangkong",
        "Pumpkin", "Bottle Gourd", "Okra",
        "Cucumber", "Eggplant", "Cabbage",
        "Cauliflower", "Tomato", "Winter Squash",
        "Curry Leaves", "Rosemary", "Mint",
        "Oregano", "Lemon Balm", "Brahmi",
        "Peppermint", "Kalmegh", "Turmeric",
        "Ashwagandha", "Lavender", "Coriander"};

string cultivation_month[61]={" ",
                            "[March to June]", "[March to June]", "[March to June]",
        "[July to October]", "[July to October]", "[July to October]",
        "[July to October]", "[July to October]", "[July to October]",
        "[March to June]", "[March to June]", "[March to June]",
        "[March to June]", "[July to October]", "[July to October]",
        "[July to October]", "[November to February]", "[November to February]",
        "[November to February]", "[November to February]", "[November to February]",
        "[November to February]", "[November to February]", "[November to February]",
        "[March to June]", "[March to June]", "[July to October]",
        "[July to October]", "[July to October]", "[November to February]",
        "[November to February]", "[November to February]", "[November to February]",
        "[November to February]", "[November to February]", "[November to February]",
        "[March to June]", "[March to June]", "[July to October]",
        "[July to October]", "[July to October]", "[July to October]",
        "[November to February]", "[November to February]", "[November to February]",
        "[November to February]", "[November to February]", "[November to February]",
        "[July to October]", "[July to October]", "[July to October]",
        "[July to October]", "[November to February]", "[November to February]",
        "[November to February]", "[November to February]", "[November to February]"};

string growing_conditions[61]={" ",
                              "Full Sun, Well-drained Soil", "Full Sun, Moist Soil", "Warm Climate, Well-drained Soil",
        "Partial Shade, Moist Soil", "Full Sun, Humid Conditions", "Shade, Moist Soil",
        "Warm Climate, Humid Conditions", "Well-drained Soil, Partial Shade", "Cool Climate, Full Sun",
        "Full Sun, Well-drained Soil", "Full Sun, Fertile Soil", "Full Sun, Moderate Water",
        "Tropical Climate, Loamy Soil", "Subtropical Climate, Humid Conditions", "Warm Climate, Sandy Soil",
        "Warm Climate, Well-drained Soil", "Full Sun, Loamy Soil", "Moist Conditions, Well-drained Soil",
        "Aquatic Conditions, Still Water", "Warm Climate, Well-drained Soil", "Full Sun, Fertile Soil",
        "Warm Climate, Moist Soil", "Full Sun, Sandy Soil", "Cool Climate, Well-drained Soil",
        "Partial Shade, Well-drained Soil", "Warm Climate, Dry Conditions", "Low Light, Moist Soil",
        "Low Light, Well-drained Soil", "Full Sun, Moist Soil", "Shade, Moist Conditions",
        "Partial Shade, Humid Conditions", "Low Light, Dry Conditions", "Full Sun, Dry Conditions",
        "Full Sun, Well-drained Soil", "Full Sun, Well-drained Soil", "Partial Shade, Sandy Soil",
        "Full Sun, Moist Soil", "Full Sun, Moist Soil", "Full Sun, Fertile Soil",
        "Full Sun, Moist Soil", "Full Sun, Well-drained Soil", "Full Sun, Fertile Soil",
        "Full Sun, Fertile Soil", "Full Sun, Loamy Soil", "Full Sun, Well-drained Soil",
        "Warm Climate, Sandy Soil", "Partial Shade, Moist Soil", "Partial Shade, Moist Soil",
        "Partial Shade, Well-drained Soil", "Partial Shade, Moist Soil", "Partial Shade, Well-drained Soil",
        "Partial Shade, Moist Soil", "Partial Shade, Moist Soil", "Full Sun, Well-drained Soil",
        "Partial Shade, Moist Soil", "Full Sun, Sandy Soil", "Full Sun, Well-drained Soil"};


string soil_type[61]={" ","Well-drained Soil", "Moist Soil", "Well-drained Soil",
        "Moist, Well-drained Soil", "Slightly Acidic, Well-drained Soil", "Moist, Well-drained Soil",
        "Well-drained Soil", "Loamy, Well-drained Soil", "Well-drained, Sandy Soil",
        "Well-drained Soil", "Fertile, Well-drained Soil", "Well-drained, Sandy Soil",
        "Well-drained, Fertile Soil", "Loamy, Well-drained Soil", "Well-drained, Sandy Soil",
        "Well-drained, Moist Soil", "Well-drained Soil", "Well-drained, Loamy Soil",
        "Loamy Soil", "Well-drained Soil", "Sandy Soil",
        "Well-drained Soil", "Loamy Soil", "Well-drained Soil",
        "Well-drained Soil", "Well-drained, Moist Soil", "Well-drained, Moist Soil",
        "Well-drained, Humus-rich Soil", "Well-drained Soil", "Well-drained Soil",
        "Well-drained Soil", "Well-drained, Fertile Soil", "Well-drained Soil",
        "Loamy, Well-drained Soil", "Well-drained, Fertile Soil", "Well-drained, Sandy Soil",
        "Moist, Well-drained Soil", "Loamy, Well-drained Soil", "Well-drained Soil",
        "Loamy, Well-drained Soil", "Well-drained Soil", "Well-drained Soil",
        "Well-drained, Sandy Soil", "Loamy, Well-drained Soil", "Well-drained Soil",
        "Loamy, Well-drained Soil", "Well-drained, Fertile Soil", "Well-drained Soil",
        "Well-drained Soil", "Well-drained, Fertile Soil", "Well-drained, Sandy Soil",
        "Well-drained, Fertile Soil", "Well-drained Soil", "Well-drained Soil"};



string water_requirement[61]={" ",
                             "Low Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Low Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Low Water Requirement",
        "Moderate Water Requirement", "Low Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Low Water Requirement",
        "Low Water Requirement", "Low Water Requirement", "Low Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Low Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement",
        "Moderate Water Requirement", "Moderate Water Requirement", "Moderate Water Requirement"};
string temperature[61]={" ","25-40°C", "25-35°C", "22-30°C",
        "22-30°C", "20-25°C", "20-30°C",
        "22-35°C", "20-30°C", "20-25°C",
        "15-30°C", "20-30°C", "20-30°C",
        "25-35°C", "25-30°C", "25-30°C",
        "25-30°C", "20-30°C", "20-30°C",
        "20-30°C", "25-30°C", "25-30°C",
        "25-30°C", "15-25°C", "20-30°C",
        "20-30°C", "15-30°C", "20-30°C",
        "20-30°C", "25-30°C", "25-30°C",
        "20-25°C", "20-30°C", "25-30°C",
        "20-25°C", "15-25°C", "20-30°C",
        "20-30°C", "20-30°C", "20-30°C",
        "20-30°C", "25-30°C", "15-25°C",
        "25-30°C", "20-30°C", "20-30°C",
        "20-30°C", "20-30°C", "20-30°C",
        "20-30°C", "20-30°C", "20-30°C"};

string diseases[61]={" ",
                        "Root rot, powdery mildew", "Leaf spot, rust", "Whitefly, aphids",
        "Leaf spot, aphids", "Caterpillars, aphids", "Powdery mildew, aphids",
        "Leaf spot, blight", "Fungal wilt, aphids", "Root rot, aphids",
        "Powdery mildew, aphids", "Rust, aphids", "Leaf spot, blight",
        "Anthracnose, powdery mildew", "Leaf spot, fruit fly", "Cucumber mosaic virus",
        "Powdery mildew, aphids", "Anthracnose, blight", "Leaf spot, aphids",
        "Root rot, fungal diseases", "Leaf spot, fruit fly", "Leaf spot, aphids",
        "Anthracnose, aphids", "Powdery mildew, aphids", "Leaf spot, root rot",
        "Leaf spot, aphids", "Root rot, aphids", "Leaf curl, rust",
        "Powdery mildew, aphids", "Fungal leaf spot, aphids", "Leaf rot, aphids",
        "Powdery mildew, aphids", "Caterpillars, aphids", "Leaf spot, root rot",
        "Powdery mildew, aphids", "Fungal wilt, aphids", "Leaf spot, aphids",
        "Leaf spot, aphids", "Cabbage aphid, root rot", "Leaf spot, aphids",
        "Fungal wilt, aphids", "Fungal leaf rot, aphids", "Root rot, aphids",
        "Blight, aphids", "Leaf curl, aphids", "Caterpillars, aphids",
        "Leaf rust, aphids", "Powdery mildew, aphids", "Leaf curl, aphids",
        "Leaf spot, aphids", "Powdery mildew, aphids", "Leaf spot, aphids"
                        };
string diseases_management[61]={" ",
                                "Use well-drained soil and avoid waterlogging.",
        "Prune infected leaves and apply fungicides.",
        "Remove whiteflies manually and use neem oil sprays.",
        "Maintain good air circulation and use organic sprays.",
        "Remove caterpillars by hand and use insect traps.",
        "Apply fungicides and reduce overhead watering.",
        "Prune infected parts and use organic fertilizers.",
        "Improve soil drainage and avoid excessive watering.",
        "Control aphids using insecticidal soaps.",
        "Apply neem oil to control fungal growth.",
        "Remove infected leaves and use rust-resistant varieties.",
        "Prune and apply systemic fungicides.",
        "Spray with copper-based fungicides and prune infected areas.",
        "Use fruit bags and apply neem oil sprays.",
        "Control pests with neem oil and remove infected plants.",
        "Improve air circulation and use organic pesticides.",
        "Prune infected branches and apply fungicides.",
        "Use insect traps and organic pest control sprays.",
        "Improve soil drainage and avoid stagnant water.",
        "Remove infected parts and use organic fungicides.",
        "Prune and spray with copper-based fungicides.",
        "Use fruit bags and neem oil sprays.",
        "Prune infected parts and spray with insecticides.",
        "Use organic pest control and remove infected plants.",
        "Wipe leaves and use mild insecticidal sprays.",
        "Remove infected parts and improve soil drainage.",
        "Use insecticidal soaps and keep leaves clean.",
        "Improve air circulation and apply fungicides.",
        "Use organic pest control and prune infected areas.",
        "Apply neem oil sprays to manage pests.",
        "Prune infected areas and use fungicides.",
        "Remove aphids and apply organic sprays.",
        "Avoid overwatering and improve soil drainage.",
        "Prune infected parts and use organic fertilizers.",
        "Control aphids and improve soil aeration.",
        "Use organic sprays and remove infected leaves.",
        "Control pests with neem oil and remove weeds.",
        "Improve drainage and apply organic fertilizers.",
        "Remove infected leaves and use pest-resistant varieties.",
        "Apply neem oil and prune infected parts.",
        "Improve drainage and use organic pest control.",
        "Prune infected parts and apply fungicides.",
        "Control pests using organic sprays.",
        "Use neem oil sprays and prune infected parts.",
        "Avoid overwatering and improve air circulation.",
        "Control pests with neem oil and apply fungicides.",
        "Remove infected leaves and use pest-resistant varieties.",
        "Prune infected parts and apply neem oil.",
        "Maintain good air circulation and use organic sprays.",
        "Use pest-resistant varieties and improve drainage.",
        "Apply neem oil sprays and prune infected parts.",
        "Prune infected parts and use organic fertilizers.",
        "Improve soil drainage and avoid waterlogging.",
        "Apply fungicides and prune infected branches.",
        "Control pests using organic sprays and neem oil."
                               };
